script: zip woocommerce-flatratepay-gateway.zip woocommerce-flatratepay-gateway.php include/ img/ readme.txt LICENSE
deploy:
  provider: releases
  skip_clean: true
  api_key:
    secure: nCE2AZ/nRewq0LrrmycTOwyWflLhhnnESjr3tySjce6u3s8cYtgDveGmYXHikAy7Te2c52s5Qn28uqqPwcX9Ma5SS1WyM9tJcKx6IHlsP1Xni+u5b0Aq88PDeU4S7EZfO1166uiYRKt6SMptljSk0W6b+y3KSrew42MFJeNm+AS75KQkcY6DiWgDNyLpbzsyTHGYGz3dRFvpcM4ELFbxWQKxSmlBBzfBHTfk2G67j7Xx3hwwRdAKPdwsx1y7rOgGXFQLYBYeugKI8s0XOy6Lf56iYFnM2FHHR3n2LJmw9+adIAG1NhIL7yG3dGlvdFU5aoCQxOfgAozSloL963BHVtG2NwCP72X0ey+u38T5lkVLTJYQZC/gzlfbBv3LcWZbgFRFjPzpxeNmXpf4sIvs2S8iinEylh++be/vPECjAmgr/BJRn6Em9YQ8hb0J8WmB0QMvLyTKLzrhFhEUpkkRu6cML8YlItmc8nlX22GAjRyJ5NwCxYHwh5DNouBfCCjglmGVl7BlkU3rhABPGx8i7+jHbmcNTZUssMIHigHbNNVz0KG0JT1U1aWnfOrjHpSBI5qaDVxTsnbuFS6D6yxWOFYC5SsWlP+jkdu+Cn5JPVByTxsHl5BkkW/O5e3KdMhxFoVCugaUv7k3LG4aI/dTSBxK8UjHDQ8yZFy/MBFZDTs=
  file: woocommerce-flatratepay-gateway.zip
  on:
    repo: GivePay/WooCommerce-FlatRatePay-Gateway
    tags: true
